export const games = [
  {
    id: 1,
    created_at: "2024-12-23T14:50:00+00:00",
    title: "Eternum",
    image: "/images/games/eternum.jpg",
    engine: "Dojo",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 2,
    created_at: "2024-12-23T14:51:00+00:00",
    title: "Dopewars",
    image: "/images/games/dopewarsbanner.jpg",
    engine: "Dojo",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 3,
    created_at: "2024-12-23T14:52:00+00:00",
    title: "Downstream",
    image: "/images/games/downstream.jpg",
    engine: "Self Built",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 4,
    created_at: "2024-12-23T14:53:00+00:00",
    title: "Kamigotchi",
    image: "/images/games/kamigotchi.png",
    engine: "MUD",
    blockchain: "Self built Layer2",
    tags: null,
  },
  {
    id: 5,
    created_at: "2024-12-23T14:54:00+00:00",
    title: "Pirate Nation",
    image: "/images/games/piratenation.jpeg",
    engine: "Self built",
    blockchain: "Self built Layer2",
    tags: null,
  },
  {
    id: 6,
    created_at: "2024-12-23T14:55:00+00:00",
    title: "Primodium",
    image: "/images/games/primodium.jpg",
    engine: "MUD",
    blockchain: "Self built Layer2",
    tags: null,
  },
  {
    id: 7,
    created_at: "2024-12-23T14:56:00+00:00",
    title: "Anybody.gg",
    image: "/images/games/anybody.jpg",
    engine: "Self Built",
    blockchain: "Base",
    tags: null,
  },
  {
    id: 8,
    created_at: "2024-12-23T14:57:00+00:00",
    title: "The Citadel",
    image: "/images/games/citadel.jpg",
    engine: "Starknet",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 9,
    created_at: "2024-12-23T14:58:00+00:00",
    title: "Biomes",
    image: "/images/games/dopewarsbanner.jpg",
    engine: "MUD",
    blockchain: "Redstone",
    tags: null,
  },
  {
    id: 10,
    created_at: "2024-12-23T14:59:00+00:00",
    title: "Eve Frontier",
    image: "/images/evefrontier.jpg",
    engine: "MUD",
    blockchain: "N/A",
    tags: null,
  },
  {
    id: 11,
    created_at: "2024-12-23T15:00:00+00:00",
    title: "Influence",
    image: "/images/games/influence.jpg",
    engine: "Self built",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 12,
    created_at: "2024-12-23T15:01:00+00:00",
    title: "This Cursed Machine",
    image: "/images/games/tcm.jpg",
    engine: "MUD",
    blockchain: "Redstone",
    tags: null,
  },
  {
    id: 13,
    created_at: "2024-12-23T15:02:00+00:00",
    title: "Pixelaw",
    image: "/images/games/pixelaw.jpg",
    engine: "Self built",
    blockchain: "Starknet",
    tags: null,
  },
];

export const allgames = [
  {
    id: 1,
    created_at: "2024-12-23T14:50:00+00:00",
    title: "Eternum",
    image: "/images/games/eternum.jpg",
    engine: "Dojo",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 2,
    created_at: "2024-12-23T14:51:00+00:00",
    title: "Dopewars",
    image: "/images/games/dopewarsbanner.jpg",
    engine: "Dojo",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 3,
    created_at: "2024-12-23T14:52:00+00:00",
    title: "Downstream",
    image: "/images/games/downstream.jpg",
    engine: "Self Built",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 4,
    created_at: "2024-12-23T14:53:00+00:00",
    title: "Kamigotchi",
    image: "/images/games/kamigotchi.png",
    engine: "MUD",
    blockchain: "Self built Layer2",
    tags: null,
  },
  {
    id: 5,
    created_at: "2024-12-23T14:54:00+00:00",
    title: "Pirate Nation",
    image: "/images/games/piratenation.jpeg",
    engine: "Self built",
    blockchain: "Self built Layer2",
    tags: null,
  },
  {
    id: 6,
    created_at: "2024-12-23T14:55:00+00:00",
    title: "Primodium",
    image: "/images/games/primodium.jpg",
    engine: "MUD",
    blockchain: "Self built Layer2",
    tags: null,
  },
  {
    id: 7,
    created_at: "2024-12-23T14:56:00+00:00",
    title: "Anybody.gg",
    image: "/images/games/anybody.jpg",
    engine: "Self Built",
    blockchain: "Base",
    tags: null,
  },
  {
    id: 8,
    created_at: "2024-12-23T14:57:00+00:00",
    title: "The Citadel",
    image: "/images/games/citadel.jpg",
    engine: "Starknet",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 9,
    created_at: "2024-12-23T14:58:00+00:00",
    title: "Biomes",
    image: "/images/games/dopewarsbanner.jpg",
    engine: "MUD",
    blockchain: "Redstone",
    tags: null,
  },
  {
    id: 10,
    created_at: "2024-12-23T14:59:00+00:00",
    title: "Eve Frontier",
    image: "/images/evefrontier.jpg",
    engine: "MUD",
    blockchain: "N/A",
    tags: null,
  },
  {
    id: 11,
    created_at: "2024-12-23T15:00:00+00:00",
    title: "Influence",
    image: "/images/games/influence.jpg",
    engine: "Self built",
    blockchain: "Starknet",
    tags: null,
  },
  {
    id: 12,
    created_at: "2024-12-23T15:01:00+00:00",
    title: "This Cursed Machine",
    image: "/images/games/tcm.jpg",
    engine: "MUD",
    blockchain: "Redstone",
    tags: null,
  },
  {
    id: 13,
    created_at: "2024-12-23T15:02:00+00:00",
    title: "Pixelaw",
    image: "/images/games/pixelaw.jpg",
    engine: "Self built",
    blockchain: "Starknet",
    tags: null,
  },
];
